### PR TITLE
Checking if zwave db file exists before opening it.

### PR DESCRIPTION
**Pull request by Bounz**

### CODE REVIEW

**Comment by genemars** [comment]
Can the xml file be stored in the same zwavelib.dll folder like it happens for _zwavenodes.xml_?

```
string codeBase = GetType().Assembly.CodeBase;
UriBuilder uri = new UriBuilder(codeBase);
string path = Uri.UnescapeDataString(uri.Path);
configFolder = Path.GetDirectoryName(path);
// configFolder is the path where to store XML data files
```

also can you rename the file to something shorter like `zwavedefs.xml` ?

**Comment by Bounz** [comment]
Ok, I'll do this. But actually it would be the folder where Mig,HomeAutoumation.dll resides, not ZWaveLib.dll. Btw, this is the same folder =)

**Comment by genemars** [comment]
good, this will also make the _zwavedefs.xml_ included in the backup file:

https://github.com/genielabs/HomeGenie/blob/master/HomeGenie/Service/BackupManager.cs#L94

g.

**Comment by Bounz** [comment]
Well, I decided to name the file p1db_custom.xml. I think it better describes the nature of file than zwavedefs.xml.
Also, including p1db into backup, increases it's size. On my installation backup archive is 2Mb now.

**Pull request merged**
